// Ghana Recreational Locations Data
const ghanaRecreationData = [
    {
        id: 1,
        name: "Kakum National Park",
        category: "park",
        region: "central",
        coordinates: { lat: 5.3556, lng: -1.3738 },
        rating: 4.7,
        description: "Famous for its canopy walkway suspended 40 meters above the forest floor. One of Ghana's most visited natural attractions.",
        image: "images/Kaku-National-Park.jpg",
        activities: ["Canopy Walk", "Bird Watching", "Nature Trails", "Wildlife Viewing"],
        location: "33km north of Cape Coast, Central Region",
        openingHours: "6:00 AM - 6:00 PM",
        entryFee: "GHS 20 (Ghanaians), GHS 50 (Foreigners)",
        contact: "+233 332 133 729",
        bestTimeToVisit: "October to March (dry season)",
        facilities: ["Visitor Center", "Gift Shop", "Restrooms", "Parking", "Treehouse Accommodation"]
    },
    {
        id: 2,
        name: "Labadi Beach",
        category: "beach",
        region: "greater-accra",
        coordinates: { lat: 5.5777, lng: -0.1355 },
        rating: 4.3,
        description: "Accra's most popular beach destination with golden sand, beach resorts, and vibrant nightlife.",
        image: "images/Labadi-Beach.jpg",
        activities: ["Swimming", "Beach Volleyball", "Horse Riding", "Live Music", "Beach Parties"],
        location: "La, Accra, Greater Accra Region",
        openingHours: "24 hours",
        entryFee: "GHS 5 - 10",
        contact: "+233 302 777 777",
        bestTimeToVisit: "Year-round",
        facilities: ["Beach Bars", "Hotels", "Restaurants", "Changing Rooms", "Security"]
    },
    {
        id: 3,
        name: "Mole National Park",
        category: "park",
        region: "northern",
        coordinates: { lat: 9.3056, lng: -1.8439 },
        rating: 4.6,
        description: "Ghana's largest wildlife park, home to elephants, antelopes, baboons, and over 300 bird species.",
        image: "images/Mole-National-Park.jpg",
        activities: ["Safari Game Drives", "Walking Safaris", "Bird Watching", "Photography"],
        location: "Larabanga, Northern Region",
        openingHours: "6:00 AM - 6:00 PM",
        entryFee: "GHS 30 (Ghanaians), GHS 75 (Foreigners)",
        contact: "+233 244 623 459",
        bestTimeToVisit: "November to April",
        facilities: ["Mole Motel", "Restaurant", "Information Center", "Airstrip"]
    },
    {
        id: 4,
        name: "Cape Coast Castle",
        category: "historical",
        region: "central",
        coordinates: { lat: 5.1053, lng: -1.2466 },
        rating: 4.8,
        description: "Historic fort and UNESCO World Heritage Site, significant in the Atlantic slave trade history.",
        image: "images/Cape-Coast-Castle.jpg",
        activities: ["Historical Tours", "Museum Visits", "Cultural Education", "Photography"],
        location: "Cape Coast, Central Region",
        openingHours: "9:00 AM - 4:30 PM",
        entryFee: "GHS 40 (Ghanaians), GHS 80 (Foreigners)",
        contact: "+233 332 142 138",
        bestTimeToVisit: "Year-round",
        facilities: ["Museum", "Gift Shop", "Tour Guides", "Parking", "Restrooms"]
    },
    {
        id: 5,
        name: "Aburi Botanical Gardens",
        category: "nature",
        region: "eastern",
        coordinates: { lat: 5.8500, lng: -0.1833 },
        rating: 4.4,
        description: "Scenic botanical garden in the hills with diverse plant species and panoramic views of Accra.",
        image: "images/Aburi-Botanical-Gardens.jpg",
        activities: ["Nature Walks", "Photography", "Picnicking", "Plant Studies", "Scenic Views"],
        location: "Aburi, Eastern Region",
        openingHours: "8:00 AM - 6:00 PM",
        entryFee: "GHS 10 (Ghanaians), GHS 20 (Foreigners)",
        contact: "+233 244 567 890",
        bestTimeToVisit: "Year-round",
        facilities: ["Walking Trails", "Picnic Areas", "Parking", "Refreshment Center"]
    },
    {
        id: 6,
        name: "Busua Beach",
        category: "beach",
        region: "western",
        coordinates: { lat: 4.7883, lng: -2.2694 },
        rating: 4.5,
        description: "Pristine beach perfect for surfing with excellent waves and beautiful sunset views.",
        image: "images/Busua-Beach.jpg",
        activities: ["Surfing", "Swimming", "Sunset Viewing", "Beach Walks", "Relaxation"],
        location: "Busua, Western Region",
        openingHours: "24 hours",
        entryFee: "Free",
        contact: "+233 312 456 789",
        bestTimeToVisit: "November to March",
        facilities: ["Surf Schools", "Beach Resorts", "Restaurants", "Bars"]
    },
    {
        id: 7,
        name: "Manhyia Palace Museum",
        category: "cultural",
        region: "ashanti",
        coordinates: { lat: 6.7000, lng: -1.6167 },
        rating: 4.6,
        description: "Former palace of the Asantehene, showcasing rich Ashanti culture and royal artifacts.",
        image: "images/Manhyia-Palace-Museum.jpg",
        activities: ["Cultural Tours", "Museum Visits", "Traditional Ceremonies", "Historical Learning"],
        location: "Kumasi, Ashanti Region",
        openingHours: "9:00 AM - 5:00 PM",
        entryFee: "GHS 15 (Ghanaians), GHS 30 (Foreigners)",
        contact: "+233 322 025 656",
        bestTimeToVisit: "Year-round",
        facilities: ["Museum", "Gift Shop", "Cultural Center", "Parking"]
    },
    {
        id: 8,
        name: "Wli Waterfalls",
        category: "nature",
        region: "eastern",
        coordinates: { lat: 7.1333, lng: 0.6000 },
        rating: 4.7,
        description: "Ghana's highest waterfall at 60 meters, located near the Togo border with beautiful hiking trails.",
        image: "images/Wli-Waterfalls.jpg",
        activities: ["Hiking", "Swimming", "Photography", "Bird Watching", "Nature Walks"],
        location: "Wli, Volta Region",
        openingHours: "7:00 AM - 5:00 PM",
        entryFee: "GHS 15 (Ghanaians), GHS 25 (Foreigners)",
        contact: "+233 244 789 123",
        bestTimeToVisit: "April to October (rainy season)",
        facilities: ["Hiking Trails", "Changing Rooms", "Local Guides", "Parking"]
    },
    {
        id: 9,
        name: "Bojo Beach",
        category: "beach",
        region: "greater-accra",
        coordinates: { lat: 5.4833, lng: -0.3667 },
        rating: 4.2,
        description: "White sand beach with clear waters, perfect for day trips and water sports from Accra.",
        image: "images/Bojo-Beach.jpg",
        activities: ["Swimming", "Jet Skiing", "Beach Games", "Boat Rides", "Relaxation"],
        location: "Bortianor, Greater Accra Region",
        openingHours: "6:00 AM - 10:00 PM",
        entryFee: "GHS 20 - 30",
        contact: "+233 302 888 999",
        bestTimeToVisit: "October to March",
        facilities: ["Beach Resort", "Restaurant", "Water Sports", "Event Halls"]
    },
    {
        id: 10,
        name: "Elmina Castle",
        category: "historical",
        region: "central",
        coordinates: { lat: 5.0833, lng: -1.3500 },
        rating: 4.8,
        description: "First European building constructed in sub-Saharan Africa, UNESCO World Heritage Site.",
        image: "images/Elmina-Castle.jpg",
        activities: ["Historical Tours", "Cultural Education", "Photography", "Museum Visits"],
        location: "Elmina, Central Region",
        openingHours: "9:00 AM - 4:30 PM",
        entryFee: "GHS 40 (Ghanaians), GHS 80 (Foreigners)",
        contact: "+233 332 142 139",
        bestTimeToVisit: "Year-round",
        facilities: ["Museum", "Tour Guides", "Gift Shop", "Parking", "Restrooms"]
    },
    {
        id: 11,
        name: "Lake Volta",
        category: "nature",
        region: "eastern",
        coordinates: { lat: 7.5000, lng: -0.1667 },
        rating: 4.3,
        description: "One of the world's largest man-made lakes, perfect for boat cruises and fishing.",
        image: "images/Lake-Volta.jpg",
        activities: ["Boat Cruises", "Fishing", "Water Sports", "Island Hopping", "Photography"],
        location: "Akosombo, Eastern Region",
        openingHours: "24 hours",
        entryFee: "Boat rides from GHS 50",
        contact: "+233 244 111 222",
        bestTimeToVisit: "November to March",
        facilities: ["Boat Services", "Hotels", "Restaurants", "Marina"]
    },
    {
        id: 12,
        name: "Paga Crocodile Pond",
        category: "nature",
        region: "northern",
        coordinates: { lat: 10.9667, lng: -1.1167 },
        rating: 4.1,
        description: "Sacred crocodile pond where visitors can safely interact with friendly crocodiles.",
        image: "images/Paga-Crocodile-Pond.jpg",
        activities: ["Crocodile Viewing", "Photography", "Cultural Tours", "Traditional Stories"],
        location: "Paga, Upper East Region",
        openingHours: "8:00 AM - 6:00 PM",
        entryFee: "GHS 10 (Ghanaians), GHS 20 (Foreigners)",
        contact: "+233 244 333 444",
        bestTimeToVisit: "November to March",
        facilities: ["Local Guides", "Parking", "Traditional Market"]
    },
    {
        id: 13,
        name: "Shai Hills Reserve",
        category: "park",
        region: "greater-accra",
        coordinates: { lat: 5.8667, lng: -0.0833 },
        rating: 4.0,
        description: "Wildlife reserve with baboons, antelopes, and ostriches, plus ancient caves and rock formations.",
        image: "images/Shai-Hills-Reserve.jpg",
        activities: ["Wildlife Viewing", "Rock Climbing", "Cave Exploration", "Hiking", "Bird Watching"],
        location: "Shai Hills, Greater Accra Region",
        openingHours: "6:00 AM - 6:00 PM",
        entryFee: "GHS 25 (Ghanaians), GHS 50 (Foreigners)",
        contact: "+233 244 555 666",
        bestTimeToVisit: "October to March",
        facilities: ["Visitor Center", "Hiking Trails", "Camping Sites", "Parking"]
    },
    {
        id: 14,
        name: "Nzulezu Stilt Village",
        category: "cultural",
        region: "western",
        coordinates: { lat: 5.1333, lng: -2.5000 },
        rating: 4.4,
        description: "Unique village built entirely on stilts over Lake Tadane, accessible only by canoe.",
        image: "images/Nzulezu-Stilt-Village.jpg",
        activities: ["Canoe Rides", "Cultural Tours", "Photography", "Traditional Crafts", "Village Life Experience"],
        location: "Beyin, Western Region",
        openingHours: "8:00 AM - 5:00 PM",
        entryFee: "GHS 30 (includes canoe ride)",
        contact: "+233 244 777 888",
        bestTimeToVisit: "November to March",
        facilities: ["Canoe Services", "Local Guides", "Craft Shop"]
    },
    {
        id: 15,
        name: "Kumasi Zoo",
        category: "entertainment",
        region: "ashanti",
        coordinates: { lat: 6.6833, lng: -1.6167 },
        rating: 3.8,
        description: "Ghana's largest zoo with diverse African wildlife and educational programs.",
        image: "images/Kumasi-Zoo.jpg",
        activities: ["Animal Viewing", "Educational Tours", "Photography", "Family Picnics"],
        location: "Kumasi, Ashanti Region",
        openingHours: "8:00 AM - 6:00 PM",
        entryFee: "GHS 8 (Ghanaians), GHS 15 (Foreigners)",
        contact: "+233 322 027 000",
        bestTimeToVisit: "Year-round",
        facilities: ["Zoo Restaurant", "Picnic Areas", "Gift Shop", "Parking", "Children's Playground"]
    },
    {
        id: 16,
        name: "Ankasa National Park",
        category: "park",
        region: "western",
        coordinates: { lat: 5.2667, lng: -2.6333 },
        rating: 4.2,
        description: "Pristine rainforest with rare butterfly species and diverse wildlife, part of UNESCO Biosphere Reserve.",
        image: "images/Ankasa-National-Park.jpg",
        activities: ["Butterfly Watching", "Forest Walks", "Bird Watching", "Research Tours", "Photography"],
        location: "Ankasa, Western Region",
        openingHours: "6:00 AM - 6:00 PM",
        entryFee: "GHS 20 (Ghanaians), GHS 40 (Foreigners)",
        contact: "+233 244 999 000",
        bestTimeToVisit: "November to March",
        facilities: ["Research Station", "Hiking Trails", "Basic Accommodation"]
    },
    {
        id: 17,
        name: "Keta Lagoon",
        category: "nature",
        region: "eastern",
        coordinates: { lat: 5.9167, lng: 0.9833 },
        rating: 4.1,
        description: "Important bird sanctuary and Ramsar Wetland site with diverse aquatic bird species.",
        image: "images/Keta-Lagoon.jpg",
        activities: ["Bird Watching", "Boat Tours", "Photography", "Fishing", "Nature Studies"],
        location: "Keta, Volta Region",
        openingHours: "6:00 AM - 6:00 PM",
        entryFee: "GHS 15 (Ghanaians), GHS 25 (Foreigners)",
        contact: "+233 244 123 456",
        bestTimeToVisit: "November to March",
        facilities: ["Boat Services", "Bird Watching Towers", "Information Center"]
    },
    {
        id: 18,
        name: "Accra Sports Stadium",
        category: "entertainment",
        region: "greater-accra",
        coordinates: { lat: 5.5667, lng: -0.1833 },
        rating: 4.0,
        description: "National stadium hosting football matches, concerts, and major cultural events.",
        image: "images/Accra-Sports-Stadium.jpg",
        activities: ["Football Matches", "Concerts", "Cultural Events", "Sports Events"],
        location: "Accra, Greater Accra Region",
        openingHours: "Event dependent",
        entryFee: "Varies by event",
        contact: "+233 302 666 777",
        bestTimeToVisit: "Check event calendar",
        facilities: ["Parking", "Food Courts", "VIP Sections", "Security"]
    },
    {
        id: 19,
        name: "Boti Falls",
        category: "nature",
        region: "eastern",
        coordinates: { lat: 6.2000, lng: -0.2667 },
        rating: 4.3,
        description: "Twin waterfalls with a natural swimming pool, surrounded by lush tropical vegetation.",
        image: "images/Boti-Falls.jpg",
        activities: ["Swimming", "Hiking", "Photography", "Nature Walks", "Picnicking"],
        location: "Boti, Eastern Region",
        openingHours: "7:00 AM - 6:00 PM",
        entryFee: "GHS 10 (Ghanaians), GHS 20 (Foreigners)",
        contact: "+233 244 789 012",
        bestTimeToVisit: "April to September",
        facilities: ["Changing Rooms", "Parking", "Local Guides", "Picnic Areas"]
    },
    {
        id: 20,
        name: "Anomabu Beach",
        category: "beach",
        region: "central",
        coordinates: { lat: 5.2000, lng: -1.2667 },
        rating: 4.1,
        description: "Peaceful fishing beach with colorful boats and authentic coastal village atmosphere.",
        image: "images/Anomabu-Beach.jpg",
        activities: ["Beach Walks", "Fishing Village Tours", "Photography", "Cultural Interaction", "Swimming"],
        location: "Anomabu, Central Region",
        openingHours: "24 hours",
        entryFee: "Free",
        contact: "+233 244 345 678",
        bestTimeToVisit: "October to March",
        facilities: ["Local Restaurants", "Fishing Boats", "Village Market"]
    },
];

// Export data for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ghanaRecreationData;
}